# toolchain-arm.cmake
SET(CMAKE_SYSTEM_NAME Linux)
SET(CMAKE_SYSTEM_PROCESSOR arm)

SET(CMAKE_C_COMPILER   arm-mol-linux-uclibcgnueabihf-gcc)
SET(CMAKE_CXX_COMPILER arm-mol-linux-uclibcgnueabihf-g++)

SET(CMAKE_FIND_ROOT_PATH  /opt/molchip/arm-molchip-linux)

SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
